### ISSUE TITLE
[Bug]: compilation errors

### ISSUE THREAD

**Issue by swervx** [Gozzim/mod-defend-city#1]
### Current Behaviour

hello I get many errors during compilation
![mod-defend-city](https://github.com/Gozzim/mod-defend-city/assets/101983666/e1fd2607-d21d-46a0-b7a5-abf3a6d2903b)

### Expected Behaviour

compile without errors

### Steps to reproduce the problem

correct the script

### AC rev. hash/commit

latest revision of Azerothcore

### Operating system

Windows 11 x64

**Comment by Gozzim** [comment]
Yeah the script is still a big WIP and hasn't been finished so far.
As can be seen from the code itself, the unfinished Readme and the failing tests :)
I will finish this when I find the time
